### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by J-Priebe** [SalesforceFoundation/python-bayeux#8]
Hello,

I have used this client, and `simple_salesforce` for auth, to successfully instantiate `BayeauxClient`. However I'm unsure of how to actually subscribe to PushTopic or other events from Salesforce. Are these implemented as "Greenlets"? Is there documentation or examples anywhere on the actual Salesforce implementation? Thank you!

**Edit**
Some more specific questions:
- do we simply call `client.subscribe(channel_name, callback)` to subscribe?
- what is the best way to access these events? Checking `client.message_queue`?
- How does one specify the replay mode (all messages in last 24 hours, all messages since event with given id, etc.)
- Is client supposed to run in its own thread? After calling `start()`, the client exits immediately, even though `self.greenlets` is non-empty. I have tried adding a `sleep` loop after running, and also creating a thread with `client.start` as the entry point, but in both cases I don't see any output from `_connect_greenlets` (which seems to be the main loop which appends message to the queue?)

**Comment by adamlincoln** [comment]
Hi @J-Priebe - thanks for the questions!  I agree that this needs some examples and better documentation - I hope to add some soon.

The good news is that if your plan is to connect to the salesforce streaming API, then there's a package specifically for that use case: salesforce-streaming-client.  It supports salesforce specific features, like replay id and publish via rest.  It handles auth via a dependency so you won't be using simple_salesforce at all.

salesforce-streaming-client doesn't have great examples (they are needed too), but the tests provide a good starting point.  The simple example client implementation at

https://github.com/SalesforceFoundation/salesforce-streaming-client/blob/master/tests/test_it.py#L90

may be enough, but to answer your questions (which are also good questions once you switch to salesforce-streaming-client):

- Start by writing a subclass of SalesforceStreamingClient, with your callback methods defined.  Then in your main code, after instantiating your client subclass, call `client.subscribe(channel_name, 'some_callback_method')`.

- Your callback method will receive each streaming event as an argument (called `connect_response_element` in the test example linked above.  Then you can do whatever you want.  The code that is receiving new events from the streaming API is in a different greenlet (if you're new to greenlets, think of them as a kind of thread) than the callbacks, so you don't have to worry about input/output in your callback blocking new incoming events.

- For replay, see the `replay` keyword parameter to `client.subscribe()`.  It's channel specific, and by default, it's set to `True`.  Here are the options for `replay`:
  - `True`: if the client has run before and has a stored replay id it saw, then use that as the replay parameter.  (This is so you can restart your client and the client just does the right thing by asking for everything that's new since it last ran.)  If the client doesn't have a stored replay id, then it sends -1 (no old events).
  - `False`: send -1 (no old events)
  - `'all'`: send -2 (all old events)
  - else send the `replay` value directly, so you can pick whatever you want.


- After calling `start()`, if you don't want to do anything else in your main code, then call `client.block()`.  Your main code will wait there, and your client will chug along, handling streaming events as they come in.  If you do want to do more in your main code after calling `start()`, you can call `client.go()`, which sets up an additional greenlet for your callbacks to execute in, so your following main code won't interfere.  (But if you use `go()`, you will have to do something to keep your main code from exiting, and `time.sleep()` is not a good option, because it will block all of the greenlets.  A `while` loop that contains a concurrent call would work.)

I hope this helps!

**Comment by J-Priebe** [comment]
Fantastic! I totally overlooked the `salesforce-streaming-client` project. I ended up calling
```
gevent.joinall(client.greenlets)
```
in my main program after starting the client, which appears to work, though I haven't set up any PushTopics yet. Happy to hear the streaming client is built to handle the threading. I will check that out and direct any further issues towards that project. Thank you for your timely feedback @adamlincoln.
